package com.danschellekens.dantanks.game;

public enum LevelUmpireStage {
	INITIAL_DELAY_BEFORE_LEVEL_BEGINS,
	MAKING_AI_SEEM_HUMAN,
	WAITING_FOR_PLAYER_TO_FIRE,
	WAITING_FOR_LEVEL_TO_RUN_ACTIONS,
	DELAY_BETWEEN_TURNS,
	DELAY_AFTER_CURRENT_PLAYER_DIES,
	FINAL_DELAY_BEFORE_SHOPPING
}
